MinSalSidPlaUsersBundle_mostrarUsuariosSinRol:
    pattern:  /mostrarUsuariosSinRol
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:mostrarUsuariosSinRol}
    
MinSalSidPlaUsersBundle_consultarUsuarioSinRolJSON:
    pattern:  /consultarUsuarioSinRolJSON
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:consultarUsuarioSinRolJSON }
    
MinSalSidPlaUsersBundle_editarUsuarioSinRol:
    pattern:  /editarUsuarioSinRol
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:editarUsuarioSinRol }

MinSalSidPlaUsersBundle_verificaCreacion:
    pattern:  /verificaCreacion
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:verificaCreacion }


#*******************
#***  USUARIOS  ****
#*******************
MinSalSidPlaUsersBundle_registerUsuarioInterno:
    pattern:  /register/{userInterno}
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:register }
    
MinSalSidPlaUsersBundle_registerUsuarioExterno:
    pattern:  /register/{userInterno}/{entId}
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:register }
    
MinSalSidPlaUsersBundle_mantMostrarUsuarios:
    pattern:  /mantMostrarUsuarios/{userInterno}/{entId}
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:mantUsers , userInterno: 'true', entId: 'Ministerios'} 

MinSalSidPlaUsersBundle_consultarUsuariosJSON:
    pattern:  /consultarUsuariosJSON/{userInterno}/{entId}
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:consultarUsuariosJSON } 
    
MinSalSidPlaUsersBundle_mantCargarUsuario:
    pattern:  /mantCargarUsuario/{userInterno}/{idUsuario}/{entId}
    defaults: { _controller: MinSalSidPlaUsersBundle:Default:mantCargarUsuario } 