#app/config/rounting.yml
MinSalSidPlaDependenciaBundle:
    resource: "@MinSalSidPlaDependenciaBundle/Resources/config/routing.yml"
    prefix:   /SidPla/

MinSalSidPlaBundle:
    resource: "@MinSalSidPlaBundle/Resources/config/routing.yml"
    prefix:   /SidPla/

MinSalSidPlaAdminBundle:
    resource: "@MinSalSidPlaAdminBundle/Resources/config/routing.yml"
    prefix:   /SidPla/

MinSalSidPlaUsersBundle:
    resource: "@MinSalSidPlaUsersBundle/Resources/config/routing.yml"
    prefix:   /SidPla/users

MinSalSidPlaReportesBundle:
    resource: "@MinSalSidPlaReportesBundle/Resources/config/routing.yml"
    prefix:   /SidPla/reportes

#Para seguridad
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password