#****************************
#*** Inventario Detallado ***
#****************************
MinSalSCAProcesosBundle_mantInventariosDet:
    pattern:  /inventario/mantInventariosDet
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventariosDet } 
    
MinSalSCAProcesosBundle_consultarInventariosDetJSON:
    pattern:  /inventario/consultarInventariosDetJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:consultarInventariosDetJSON } 

MinSalSCAProcesosBundle_mantInventarioDetEdicion:
    pattern:  /inventario/mantInventarioDetEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantInventarioDetEdicion }

MinSalSCAProcesosBundle_mantCargarInventarioDet:
    pattern:  /inventario/mantCargarInventarioDet/{invDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAInventariosDet:mantCargarInventarioDet } 
    
    
#****************************
#***    Registro Ventas   ***
#****************************
MinSalSCAProcesosBundle_mantRegVenta:
    pattern:  /RegVenta/mantRegVenta
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegVenta:mantRegVenta } 
    
MinSalSCAProcesosBundle_consultarRegVentaJSON:
    pattern:  /RegVenta/consultarRegVentaJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegVenta:consultarRegVentaJSON } 

MinSalSCAProcesosBundle_mantRegVentaEdicion:
    pattern:  /RegVenta/mantRegVentaEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegVenta:mantRegVentaEdicion }

MinSalSCAProcesosBundle_mantCargarRegVenta:
    pattern:  /RegVenta/mantCargarRegVenta/{RegVentaId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegVenta:mantCargarRegVenta } 
MinSalSCAProcesosBundle_getGradoRV:
    pattern:  /RegVenta/getGradoRV/{CuoId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegVenta:getGradoRV } 
    
#********************************
#*** Registro Detalle Menusal ***
#********************************
MinSalSCAProcesosBundle_mantRegMensual:
    pattern:  /RegMensual/mantRegMensual
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegMensual:mantRegMensual } 
    
MinSalSCAProcesosBundle_consultarRegMensualJSON:
    pattern:  /RegMensual/consultarRegMensualJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegMensual:consultarRegMensualJSON } 

MinSalSCAProcesosBundle_mantRegMensualEdicion:
    pattern:  /RegMensual/mantRegMensualEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegMensual:mantRegMensualEdicion }

MinSalSCAProcesosBundle_mantCargarRegMensual:
    pattern:  /RegMensual/mantCargarRegMensual/{RegMenId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCARegMensual:mantCargarRegMensual } 
    
        
    
    
#*****************************
#*** Solicitud Importacion ***
#*****************************
MinSalSCAProcesosBundle_mantSolImportacionIngreso:
    pattern:  /Solicitud/Importacion/Ingreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionIngreso } 
    
MinSalSCAProcesosBundle_consultarSolImportacionDetJSON:
    pattern:  /Solicitud/Importacion/Consultar/{etpId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:consultarSolImportacionJSON } 

MinSalSCAProcesosBundle_mantSolImportacionEdicion:
    pattern:  /Solicitud/Importacion/Edicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionEdicion }

MinSalSCAProcesosBundle_mantCargarSolImportacion:
    pattern:  /Solicitud/Importacion/Cargar/{impDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantCargarSolImportacion } 
    
MinSalSCAProcesosBundle_cambiarEstadoImportacion:
    pattern:  /Solicitud/Importacion/CambiarEstado/{impDetId}/{traId}/update
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:cambiarEstado }

MinSalSCAProcesosBundle_getCuotasImportacion:
    pattern:  /Solicitud/Importacion/getCuotas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getCuotas }

#Visualizacion de solicitudes de importacion por empresa
MinSalSCAProcesosBundle_mantSolImportacionVerSolicitudes:
    pattern:  /Solicitud/Importacion/VerSolicitudes
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionVerSolicitudes } 
    
MinSalSCAProcesosBundle_verSolImportacionesJSON:
    pattern:  /Solicitud/Importacion/VerSolicitudes/Consultar
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:verSolImportacionesJSON } 

MinSalSCAProcesosBundle_getSearchEstadosImportacion:
    pattern:  /Solicitud/Importacion/getSearchEstados 
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getSearchEstados }

MinSalSCAProcesosBundle_getSearchEtapasImportacion:
    pattern:  /Solicitud/Importacion/getSearchEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getSearchEtapas }
    
    
#MinSalSCAProcesosBundle_mantSolImportacionVerSolicitudesMINSAL:
#    pattern:  /Solicitud/Importacion/VerSolicitudes/{etpEntidad}/
#    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:mantSolImportacionVerSolicitudes, etpEntidad: 'MINSAL'}
    
MinSalSCAProcesosBundle_getEtapasImportacion:
    pattern:  /Solicitud/Importacion/getEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolImportacion:getEtapas }



#*****************************
#***    Solicitud Local    ***
#*****************************
### MENU ###
MinSalSCAProcesosBundle_mantSolLocalIngreso:
    pattern:  /Solicitud/Local/Ingreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalIngreso }
    
MinSalSCAProcesosBundle_consultarSolLocalDetJSON:
    pattern:  /Solicitud/Local/Consultar/{etpId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:consultarSolLocalJSON }

MinSalSCAProcesosBundle_mantSolLocalEdicion:
    pattern:  /Solicitud/Local/Edicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalEdicion }

MinSalSCAProcesosBundle_mantCargarSolLocal:
    pattern:  /Solicitud/Local/Cargar/{localDetId}
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantCargarSolLocal }
    
MinSalSCAProcesosBundle_cambiarEstadoLocal:
    pattern:  /Solicitud/Local/CambiarEstado/{localDetId}/{traId}/update
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:cambiarEstado }

MinSalSCAProcesosBundle_getCuotasLocal:
    pattern:  /Solicitud/Local/getCuotas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getCuotas }

MinSalSCAProcesosBundle_getProveedoresLocal:
    pattern:  /Solicitud/Local/getProveedores
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getProveedores }

#Visualizacion de solicitudes Locales por empresa
### MENU ###
MinSalSCAProcesosBundle_mantSolLocalVerSolicitudes:
    pattern:  /Solicitud/Local/VerSolicitudes
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:mantSolLocalVerSolicitudes } 
    
MinSalSCAProcesosBundle_verSolLocalesJSON:
    pattern:  /Solicitud/Local/VerSolicitudes/Consultar
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:verSolLocalesJSON } 
    
MinSalSCAProcesosBundle_verVentasJSON:
    pattern:  /Solicitud/Local/VerVentas/Consultar
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:verVentasJSON } 

MinSalSCAProcesosBundle_getSearchEstadosLocal:
    pattern:  /Solicitud/Local/getSearchEstados 
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getSearchEstados }

MinSalSCAProcesosBundle_getSearchEtapasLocal:
    pattern:  /Solicitud/Local/getSearchEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getSearchEtapas }
    
MinSalSCAProcesosBundle_getEtapasLocal:
    pattern:  /Solicitud/Local/getEtapas
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASolLocal:getEtapas }
    
#*********************************************
#***    Procesos Automatizados Publicos    ***
#*********************************************
MinSalSCAProcesosBundle_ExpiracionSolicitudes:
    pattern:  /Scheduled/Anon/Process/ExpiracionSolicitudes
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCASchAnonProcess:expiracionSolicitudes } 
    
    
#*****************************
#***  Carga de NIT/NRC MH  ***
#*****************************
MinSalSCAProcesosBundle_mantListadoMHVer:
    pattern:  /ListadoMH/mantListadoMHVer
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAListadoMH:mantListadoMHVer } 

MinSalSCAProcesosBundle_mantListadoMHIngreso:
    pattern:  /ListadoMH/mantListadoMHIngreso
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAListadoMH:mantListadoMHIngreso } 

MinSalSCAProcesosBundle_consultarListadoMHJSON:
    pattern:  /ListadoMH/consultarListadoMHJSON
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAListadoMH:consultarListadoMHJSON } 

MinSalSCAProcesosBundle_mantListadoMHEdicion:
    pattern:  /ListadoMH/mantListadoMHEdicion
    defaults: { _controller: MinSalSCAProcesosBundle:AccionSCAListadoMH:mantListadoMHEdicion } 
